=== gdosborne/CoreSource/TFS/Tools/Console/UpdateVersionSharp/UpdateVersion.Projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by Greg Osborne (Myself) -->
<!-- W3C Schema generated by XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="build">
		<xs:complexType/>
	</xs:element>
	<xs:element name="detail">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="level" minOccurs="4" maxOccurs="4"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="level">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="build" />
						<xs:enumeration value="major"/>
						<xs:enumeration value="minor"/>
						<xs:enumeration value="revision"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="method" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="day"/>
						<xs:enumeration value="dayvalue"/>
						<xs:enumeration value="fixed"/>
						<xs:enumeration value="ignore"/>
						<xs:enumeration value="increment"/>
						<xs:enumeration value="incrementeachday"/>
						<xs:enumeration value="incrementreseteachday"/>
						<xs:enumeration value="month"/>
						<xs:enumeration value="year"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parameter" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="major">
		<xs:complexType/>
	</xs:element>
	<xs:element name="method">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="day"/>
						<xs:enumeration value="dayvalue"/>
						<xs:enumeration value="dayvaluefrom"/>
						<xs:enumeration value="fixed"/>
						<xs:enumeration value="ignore"/>
						<xs:enumeration value="increment"/>
						<xs:enumeration value="incrementeachday"/>
						<xs:enumeration value="incrementreseteachday"/>
						<xs:enumeration value="month"/>
						<xs:enumeration value="random"/>
						<xs:enumeration value="secondvalue"/>
						<xs:enumeration value="secondvaluefrom"/>
						<xs:enumeration value="twodigityear"/>
						<xs:enumeration value="year"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="methods">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="method" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="minor">
		<xs:complexType/>
	</xs:element>
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="major"/>
				<xs:element ref="minor"/>
				<xs:element ref="build"/>
				<xs:element ref="revision"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="path" type="xs:anyURI"/>
	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="path"/>
				<xs:element ref="schema"/>
			</xs:sequence>
			<xs:attribute name="name" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="projects">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="project" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="revision">
		<xs:complexType/>
	</xs:element>
	<xs:element name="schema">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="parameters"/>
				<xs:element ref="detail"/>
			</xs:choice>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="daily"/>
						<xs:enumeration value="default"/>
						<xs:enumeration value="fixed_increment"/>
						<xs:enumeration value="fixed_increment_mini"/>
						<xs:enumeration value="increment_daily"/>
						<xs:enumeration value="increment_revision"/>
						<xs:enumeration value="increment_revision_by_day"/>
						<xs:enumeration value="standard"/>
						<xs:enumeration value="static_increment_daily"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="lastbuilddate">
				<xs:simpleType>
					<xs:restriction base="xs:date">
						<xs:enumeration value="2020-07-21"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="schemas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="schema" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="updateversion.projects">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="schemas"/>
				<xs:element ref="methods"/>
				<xs:element ref="projects"/>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gdosborne/CoreSource/TFS/Tools/Console/UpdateVersionSharp/UpdateVersion.Projects.xml
<?xml version="1.0" encoding="utf-8"?>
<updateversion.projects version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Program%20Files/UpdateVersion/UpdateVersion.Projects.xsd">
	<schemas>
		<schema name="default">
			<detail>
				<level name="major" method="ignore"/>
				<level name="minor" method="ignore"/>
				<level name="build" method="ignore"/>
				<level name="revision" method="ignore"/>
			</detail>
		</schema>
		<schema name="increment_revision">
			<detail>
				<level name="major" method="ignore"/>
				<level name="minor" method="ignore"/>
				<level name="build" method="ignore"/>
				<level name="revision" method="increment"/>
			</detail>
		</schema>
		<schema name="increment_revision_by_day">
			<detail>
				<level name="major" method="ignore"/>
				<level name="minor" method="ignore"/>
				<level name="build" method="dayvalue"/>
				<level name="revision" method="incrementreseteachday"/>
			</detail>
		</schema>
		<schema name="daily">
			<detail>
				<level name="major" method="year"/>
				<level name="minor" method="month"/>
				<level name="build" method="day"/>
				<level name="revision" method="incrementreseteachday"/>
			</detail>
		</schema>
		<schema name="fixed_increment">
			<detail>
				<level name="major" method="fixed"/>
				<level name="minor" method="fixed"/>
				<level name="build" method="fixed"/>
				<level name="revision" method="increment"/>
			</detail>
		</schema>
		<schema name="fixed_increment_mini">
			<detail>
				<level name="major" method="fixed"/>
				<level name="minor" method="fixed"/>
				<level name="build" method="increment"/>
				<level name="revision" method="incrementreseteachday"/>
			</detail>
		</schema>
		<schema name="static_increment_daily">
			<detail>
				<level name="major" method="year"/>
				<level name="minor" method="month"/>
				<level name="build" method="incrementeachday"/>
				<level name="revision" method="incrementreseteachday"/>
			</detail>
		</schema>
		<schema name="increment_daily">
			<detail>
				<level name="major" method="ignore"/>
				<level name="minor" method="ignore"/>
				<level name="build" method="incrementeachday"/>
				<level name="revision" method="incrementreseteachday"/>
			</detail>
		</schema>
		<schema name="standard">
			<detail>
				<level name="major" method="ignore"/>
				<level name="minor" method="ignore"/>
				<level name="build" method="increment"/>
				<level name="revision" method="incrementreseteachday"/>
			</detail>
		</schema>
	</schemas>
	<methods>
		<method name="ignore"/>
		<method name="increment"/>
		<method name="incrementeachday"/>
		<method name="incrementreseteachday"/>
		<method name="random"/>
		<method name="dayvalue"/>
		<method name="dayvaluefrom"/>
		<method name="secondvalue"/>
		<method name="secondvaluefrom"/>
		<method name="fixed"/>
		<method name="year"/>
		<method name="twodigityear"/>
		<method name="month"/>
		<method name="day"/>
	</methods>
	<projects>

	</projects>
</updateversion.projects>
