=== gdosborne/CoreSource/TFS/Tools/WPF/GregOsborne.PasswordManager/GregOsborne.PasswordManager/Themes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="themes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="theme">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="visualelement">
                <xs:complexType>
                  <xs:attribute name="type" type="xs:string" use="required" />
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="value" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gdosborne/CoreSource/TFS/Tools/WPF/GregOsborne.PasswordManager/GregOsborne.PasswordManager/Themes.xml
<?xml version="1.0" encoding="utf-8" ?>
<themes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com themes.xsd">
  <theme name="Default">
    <visualelement type="solidcolorbrush" name="ActiveCaptionBrush" value="#FF515151" />
    <visualelement type="solidcolorbrush" name="WindowBrush" value="#FFF0F8FF" />
    <visualelement type="solidcolorbrush" name="ActiveCaptionTextBrush" value="#FFF0F8FF" />
    <visualelement type="solidcolorbrush" name="BorderBrush" value="#FF191970" />
    <visualelement type="solidcolorbrush" name="WindowTextBrush" value="#FF000000" />
    <visualelement type="double" name="FontSize" value="14.0" />
  </theme>
  <theme name="Blue">
    <visualelement type="solidcolorbrush" name="ActiveCaptionBrush" value="#FF5151FF" />
    <visualelement type="solidcolorbrush" name="WindowBrush" value="#FFF0F8FF" />
    <visualelement type="solidcolorbrush" name="ActiveCaptionTextBrush" value="#FFF0F8FF" />
    <visualelement type="solidcolorbrush" name="BorderBrush" value="#FF191970" />
    <visualelement type="solidcolorbrush" name="WindowTextBrush" value="#FF000000" />
    <visualelement type="double" name="FontSize" value="14.0" />
  </theme>
  <theme name="Orange">
    <visualelement type="solidcolorbrush" name="ActiveCaptionBrush" value="#FFC98000" />
    <visualelement type="solidcolorbrush" name="WindowBrush" value="#FFF0F8FF" />
    <visualelement type="solidcolorbrush" name="ActiveCaptionTextBrush" value="#FFF0F8FF" />
    <visualelement type="solidcolorbrush" name="BorderBrush" value="#FF191970" />
    <visualelement type="solidcolorbrush" name="WindowTextBrush" value="#FF000000" />
    <visualelement type="double" name="FontSize" value="14.0" />
  </theme>
</themes>
